Added status and navigation
hmrc/digital-disclosure-service-frontend pull request #390
Opened 2023-01-30 14:53 UTC by chetan-jain-atos

2023-01-30 15:06 UTC, burns238 requested changes

2023-01-30 15:06 UTC, burns238 commented on app/models/store/disclosure/OtherLiabilities.scala
> +    case OtherLiabilities(Some(_), Some(_), Some(_), Some(_)) => true
This breaks the completion logic. If a user doesn't select Other or Inheritance Tax then they won't be taken to those middle pages and so the section will never be complete

2023-01-30 15:08 UTC, msatta approved these changes

2023-01-31 10:21 UTC, msatta submitted a review, later dismissed

2023-01-31 13:49 UTC, burns238 approved these changes

2023-01-31 13:49 UTC, merged