DDS2-616: Navigation for DoYouHaveAnEmailAddress page
hmrc/digital-disclosure-service-frontend pull request #45
Opened 2022-09-27 16:03 UTC by msatta

2022-09-27 16:25 UTC, burns238 requested changes

2022-09-27 16:25 UTC, burns238 commented on app/navigation/NotificationNavigator.scala
> +      case None => routes.OnshoreLiabilitiesController.onPageLoad(NormalMode)
If it's None we should go back to DoYouHaveAnEmailAddressPage

2022-09-27 16:33 UTC, chetan-jain-atos approved these changes

2022-09-28 08:10 UTC, burns238 approved these changes

2022-09-28 08:11 UTC, merged